---
title: "Randall Pruim"
subtitle: "Professor of Mathematics and Statistics, Calvin University"
editor: 
  markdown: 
    wrap: 72
    
# bibliography: "bib/Pruim-pubs.bib"
# biblio-style: "../CV/bib/rjp-apa-cv.csl"
# nocite: |
#   @Pruim:2018:FASt, @Schoning:1998, @Wegner:Complexity:2005
---

```{r, include = FALSE, message = FALSE}
knitr::opts_chunk$set(
  echo = FALSE
)
```


### CV

You can find my CV
[here](https://github.com/rpruim/CV/blob/master/Randall_Pruim_CV.pdf).
Otherwise, see below for some of the highlights (and some things not on
the CV).

### Talks

You can find slides from some of my talks
[here](talks.html).

### Teaching

Find out what I've taught and access some teaching resources [here](teaching.html).

### Integrated Ethics Labs

I'm part of the Integrated Ethics Labs team.  Find out more at 
[integratedethicslabs.org](https://integratedethicslabs.org)

### Books

#### Traditionally Published

Pruim, Randall. 2018. *Foundations and Applications of Statistics: An
Introduction Using R*. 2nd ed. Vol. 28. Pure and Applied Undergraduate
Texts. Providence, RI: American Mathematical Society.
<https://www.ams.org/publications/authors/books/postpub/amstext-28>.

Schöning, Uwe, and Pruim, Randall. 1998. *Gems of Theoretical Computer
Science*. Berlin: Springer-Verlag.

Wegener, Ingo. 2005. *Complexity Theory: Exploring the Limits of
Efficient Algorithms*. Berlin: Springer-Verlag.

#### Online

Kaplan, Daniel, and Pruim, Randall. 2022. 
[*Statistical Modeling: A Fresh Approach*](https://statistical-modeling.netlify.app/).
